[build]
  # Directory to change to before starting a build
  base = "."
  # Directory that contains the deploy-ready HTML files and assets
  publish = "build/"
  # Default build command
  command = "npm run build"
  # Functions directory (disabled for frontend-only deployment)
  # functions = "netlify/functions/"

[build.environment]
  # Node.js version to use
  NODE_VERSION = "18"
  # Python version for functions (use 3.11 for better package compatibility)
  # PYTHON_VERSION = "3.11"

# Redirects for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
